let Students = [
    {
      id: 1,
      name: "Aarav Sharma",
      age: 20,
      city: "Delhi",
      state: "Delhi",
      course: "BCA",
      email: "aarav1@gmail.com",
    },
    {
      id: 2,
      name: "Vivaan Verma",
      age: 21,
      city: "Lucknow",
      state: "Uttar Pradesh",
      course: "B.Tech",
      email: "vivaan2@gmail.com",
    },
    {
      id: 3,
      name: "Aditya Singh",
      age: 19,
      city: "Jaipur",
      state: "Rajasthan",
      course: "BSc",
      email: "aditya3@gmail.com",
    },
    {
      id: 4,
      name: "Arjun Patel",
      age: 22,
      city: "Ahmedabad",
      state: "Gujarat",
      course: "B.Com",
      email: "arjun4@gmail.com",
    },
    {
      id: 5,
      name: "Krishna Kumar",
      age: 20,
      city: "Patna",
      state: "Bihar",
      course: "BCA",
      email: "krishna5@gmail.com",
    },
    {
      id: 6,
      name: "Rohan Gupta",
      age: 23,
      city: "Kanpur",
      state: "Uttar Pradesh",
      course: "BBA",
      email: "rohan6@gmail.com",
    },
    {
      id: 7,
      name: "Rahul Yadav",
      age: 21,
      city: "Gurgaon",
      state: "Haryana",
      course: "MBA",
      email: "rahul7@gmail.com",
    },
    {
      id: 8,
      name: "Ankit Mishra",
      age: 20,
      city: "Prayagraj",
      state: "Uttar Pradesh",
      course: "BSc",
      email: "ankit8@gmail.com",
    },
    {
      id: 9,
      name: "Sahil Jain",
      age: 22,
      city: "Indore",
      state: "Madhya Pradesh",
      course: "BCA",
      email: "sahil9@gmail.com",
    },
    {
      id: 10,
      name: "Kunal Mehta",
      age: 19,
      city: "Mumbai",
      state: "Maharashtra",
      course: "B.Com",
      email: "kunal10@gmail.com",
    },

    {
      id: 11,
      name: "Harsh Agarwal",
      age: 21,
      city: "Bareilly",
      state: "Uttar Pradesh",
      course: "BCA",
      email: "harsh11@gmail.com",
    },
    {
      id: 12,
      name: "Deepak Sharma",
      age: 22,
      city: "Chandigarh",
      state: "Punjab",
      course: "B.Tech",
      email: "deepak12@gmail.com",
    },
    {
      id: 13,
      name: "Vikas Kumar",
      age: 23,
      city: "Ranchi",
      state: "Jharkhand",
      course: "MBA",
      email: "vikas13@gmail.com",
    },
    {
      id: 14,
      name: "Manish Pandey",
      age: 20,
      city: "Varanasi",
      state: "Uttar Pradesh",
      course: "BSc",
      email: "manish14@gmail.com",
    },
    {
      id: 15,
      name: "Suresh Reddy",
      age: 21,
      city: "Hyderabad",
      state: "Telangana",
      course: "B.Tech",
      email: "suresh15@gmail.com",
    },
    {
      id: 16,
      name: "Ajay Singh",
      age: 19,
      city: "Bhopal",
      state: "Madhya Pradesh",
      course: "BCA",
      email: "ajay16@gmail.com",
    },
    {
      id: 17,
      name: "Pankaj Goyal",
      age: 22,
      city: "Rohtak",
      state: "Haryana",
      course: "MCA",
      email: "pankaj17@gmail.com",
    },
    {
      id: 18,
      name: "Mohit Chauhan",
      age: 20,
      city: "Dehradun",
      state: "Uttarakhand",
      course: "BBA",
      email: "mohit18@gmail.com",
    },
    {
      id: 19,
      name: "Nikhil Sharma",
      age: 21,
      city: "Shimla",
      state: "Himachal Pradesh",
      course: "BSc",
      email: "nikhil19@gmail.com",
    },
    {
      id: 20,
      name: "Tarun Kapoor",
      age: 23,
      city: "Amritsar",
      state: "Punjab",
      course: "MBA",
      email: "tarun20@gmail.com",
    },

    {
      id: 21,
      name: "Raj Malhotra",
      age: 20,
      city: "Ludhiana",
      state: "Punjab",
      course: "BCA",
      email: "raj21@gmail.com",
    },
    {
      id: 22,
      name: "Amit Tiwari",
      age: 21,
      city: "Gwalior",
      state: "Madhya Pradesh",
      course: "BSc",
      email: "amit22@gmail.com",
    },
    {
      id: 23,
      name: "Sanjay Das",
      age: 22,
      city: "Kolkata",
      state: "West Bengal",
      course: "B.Com",
      email: "sanjay23@gmail.com",
    },
    {
      id: 24,
      name: "Ritesh Sinha",
      age: 19,
      city: "Gaya",
      state: "Bihar",
      course: "BCA",
      email: "ritesh24@gmail.com",
    },
    {
      id: 25,
      name: "Ashish Gupta",
      age: 20,
      city: "Noida",
      state: "Uttar Pradesh",
      course: "B.Tech",
      email: "ashish25@gmail.com",
    },
    {
      id: 26,
      name: "Praveen Kumar",
      age: 21,
      city: "Faridabad",
      state: "Haryana",
      course: "BBA",
      email: "praveen26@gmail.com",
    },
    {
      id: 27,
      name: "Sunil Kumar",
      age: 22,
      city: "Agra",
      state: "Uttar Pradesh",
      course: "MBA",
      email: "sunil27@gmail.com",
    },
    {
      id: 28,
      name: "Dinesh Patel",
      age: 20,
      city: "Surat",
      state: "Gujarat",
      course: "B.Com",
      email: "dinesh28@gmail.com",
    },
    {
      id: 29,
      name: "Yash Thakur",
      age: 19,
      city: "Raipur",
      state: "Chhattisgarh",
      course: "BSc",
      email: "yash29@gmail.com",
    },
    {
      id: 30,
      name: "Abhishek Singh",
      age: 23,
      city: "Meerut",
      state: "Uttar Pradesh",
      course: "MCA",
      email: "abhishek30@gmail.com",
    },

    {
      id: 31,
      name: "Lokesh Yadav",
      age: 20,
      city: "Alwar",
      state: "Rajasthan",
      course: "BCA",
      email: "lokesh31@gmail.com",
    },
    {
      id: 32,
      name: "Hemant Sharma",
      age: 21,
      city: "Udaipur",
      state: "Rajasthan",
      course: "B.Com",
      email: "hemant32@gmail.com",
    },
    {
      id: 33,
      name: "Ravi Verma",
      age: 22,
      city: "Jodhpur",
      state: "Rajasthan",
      course: "BSc",
      email: "ravi33@gmail.com",
    },
    {
      id: 34,
      name: "Karan Malhotra",
      age: 23,
      city: "Delhi",
      state: "Delhi",
      course: "MBA",
      email: "karan34@gmail.com",
    },
    {
      id: 35,
      name: "Sumit Arora",
      age: 19,
      city: "Panipat",
      state: "Haryana",
      course: "BCA",
      email: "sumit35@gmail.com",
    },
    {
      id: 36,
      name: "Naveen Joshi",
      age: 20,
      city: "Nainital",
      state: "Uttarakhand",
      course: "BBA",
      email: "naveen36@gmail.com",
    },
    {
      id: 37,
      name: "Gaurav Saxena",
      age: 21,
      city: "Moradabad",
      state: "Uttar Pradesh",
      course: "B.Tech",
      email: "gaurav37@gmail.com",
    },
    {
      id: 38,
      name: "Tejas Desai",
      age: 22,
      city: "Vadodara",
      state: "Gujarat",
      course: "B.Com",
      email: "tejas38@gmail.com",
    },
    {
      id: 39,
      name: "Anurag Shukla",
      age: 23,
      city: "Sitapur",
      state: "Uttar Pradesh",
      course: "MBA",
      email: "anurag39@gmail.com",
    },
    {
      id: 40,
      name: "Rajat Bansal",
      age: 20,
      city: "Hisar",
      state: "Haryana",
      course: "BCA",
      email: "rajat40@gmail.com",
    },

    {
      id: 41,
      name: "Akash Singh",
      age: 21,
      city: "Ghaziabad",
      state: "Uttar Pradesh",
      course: "BSc",
      email: "akash41@gmail.com",
    },
    {
      id: 42,
      name: "Shubham Gupta",
      age: 22,
      city: "Mathura",
      state: "Uttar Pradesh",
      course: "B.Com",
      email: "shubham42@gmail.com",
    },
    {
      id: 43,
      name: "Vivek Tandon",
      age: 19,
      city: "Ambala",
      state: "Haryana",
      course: "BBA",
      email: "vivek43@gmail.com",
    },
    {
      id: 44,
      name: "Aman Sharma",
      age: 20,
      city: "Karnal",
      state: "Haryana",
      course: "BCA",
      email: "aman44@gmail.com",
    },
    {
      id: 45,
      name: "Rohit Kumar",
      age: 21,
      city: "Begusarai",
      state: "Bihar",
      course: "BSc",
      email: "rohit45@gmail.com",
    },
    {
      id: 46,
      name: "Mayank Jain",
      age: 22,
      city: "Kota",
      state: "Rajasthan",
      course: "B.Tech",
      email: "mayank46@gmail.com",
    },
    {
      id: 47,
      name: "Tushar Gupta",
      age: 23,
      city: "Delhi",
      state: "Delhi",
      course: "MBA",
      email: "tushar47@gmail.com",
    },
    {
      id: 48,
      name: "Shivam Dubey",
      age: 19,
      city: "Satna",
      state: "Madhya Pradesh",
      course: "BCA",
      email: "shivam48@gmail.com",
    },
    {
      id: 49,
      name: "Arpit Jain",
      age: 20,
      city: "Jaipur",
      state: "Rajasthan",
      course: "B.Com",
      email: "arpit49@gmail.com",
    },
    {
      id: 50,
      name: "Dev Kumar",
      age: 21,
      city: "Patiala",
      state: "Punjab",
      course: "BSc",
      email: "dev50@gmail.com",
    },
  ];

  export {Students}